#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed gimp tldr fzf rofi-wayland zsh
sudo pacman -S ttf-font-awesome waybar ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols --noconfirm --needed
sudo pacman -S hyprlock --noconfirm --needed
sudo pacman -S ghostty --noconfirm --needed
sudo pacman -S hyprpaper --noconfirm --needed
paru -Syu wlogout-git --noconfirm --needed
