#!/usr/bin/bash

sudo pacman -S ttf-font-awesome waybar ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols --noconfirm --needed
sudo pacman -S hyprlock --noconfirm --needed
sudo pacman -S hyprpaper pavucontrol --noconfirm --needed
