#!/usr/bin/bash

sudo ln -sf $HOME/dev/dotfiles/ghostty/ $HOME/.config/
sudo ln -sf $HOME/dev/dotfiles/tmux/ $HOME/.config/
sudo ln -sf $HOME/dev/dotfiles/nvim/ $HOME/.config/
sudo ln -sf $HOME/dev/dotfiles/.zshrc $HOME/
