#!/usr/bin/bash

sudo ln -sf $HOME/dev/dotfiles/ghostty/ $HOME/.config/
sudo ln -sf $HOME/dev/dotfiles/tmux/ $HOME/.config/
sudo ln -sf $HOME/dev/dotfiles/nvim/ $HOME/.config/
sudo ln -sf $HOME/dev/dotfiles/wofi/ $HOME/.config/
sudo rm -rf $HOME/.config/hypr/
sudo ln -sf $HOME/dev/dotfiles/hypr/ $HOME/.config/
sudo ln -sf $HOME/dev/dotfiles/waybar/ $HOME/.config/
sudo ln -sf $HOME/dev/dotfiles/.zshrc $HOME/
