#!/usr/bin/bash

sudo pacman -S --noconfirm --needed fastfetch unzip xclip wofi npm nodejs blueberry networkmanager network-manager-applet
sudo pacman -S --noconfirm --needed lua-language-server  
sudo pacman -S ghostty --noconfirm --needed
sudo pacman -S --noconfirm --needed gimp tldr fzf zsh 
