#!/usr/bin/bash

pacman -S --noconfirm --needed spotify-launcher  
paru -Sy zen-browser-bin
sudo pacman -S --noconfirm --needed fastfetch 
sudo pacman -S --noconfirm --needed openjdk-21-jre lua-language-server lazygit autopep8 pyright python-pip
sudo pacman -S --noconfirm --needed wl-clipboard
sudo pacman -S ghostty --noconfirm --needed
sudo pacman -S --noconfirm --needed gimp tldr fzf rofi-wayland zsh
